version: "3"

networks:
  mfnet:

services:
  filter_svc:
    image: dmoreira/prov-filter-svc
    restart: always
    ports:
      - 50051:50051
    volumes:
      - "./:/input"
      - "/data/NC2017_Dev1_Beta4:/data"
    command:
      - "--url=http://faiss1:8080/search"
      - "--url=http://faiss2:8080/search"
      - "--url=http://faiss3:8080/search"
    networks:
      - mfnet

  faiss1:
    image: dmoreira/prov-index-svc
    restart: always
    volumes:
      - "./index_svc:/data"
    command:
      - "--index=/data/index_1.faiss"
      - "--map=/data/index_1.faiss.map.npy"
      - "--port=8080"
    networks:
      - mfnet

  faiss2:
    image: dmoreira/prov-index-svc
    restart: always
    volumes:
      - "./index_svc:/data"
    command:
      - "--index=/data/index_2.faiss"
      - "--map=/data/index_2.faiss.map.npy"
      - "--port=8080"
    networks:
      - mfnet

  faiss3:
    image: dmoreira/prov-index-svc
    restart: always
    volumes:
      - "./index_svc:/data"
    command:
      - "--index=/data/index_3.faiss"
      - "--map=/data/index_3.faiss.map.npy"
      - "--port=8080"
    networks:
      - mfnet
